name: ${project.name}
main: br.com.strixcloud.lstop.StrixLSTop
version: ${project.version}
author: StrixCloud
load: POSTWORLD
softdepend:
  - Legendchat
  - nChat
  - HolographicDisplays
commands:
  topdonators:
    aliases:
      - topdoadores
    description: Sends the top donators of Lojasquare
  strixlstop:
    aliases:
      - lstop
      - lojasquaretop
    description: Main command of plugin